name: Build and deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.4]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3
      - run: pnpm install
      - run: pnpm run check-format
      - run: pnpm run lint
      - run: pnpm run build

  deploy-server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'JustUtahCoders'
    needs: [build]
    env:
      ENV_VARS_YAML: ${{ secrets.ENV_VARS_YAML }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.3
      - run: pnpm install
      - run: pnpm run build
      # Upload frontend assets to GCP bucket
      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: dist
          destination: ${{ secrets.GCP_FRONTEND_BUCKET }}

      # App Engine deployment
      - run: echo "$ENV_VARS_YAML" > env-vars.yaml
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
